# CAUTION! 
# Branch name comments are crucial for `nix run .#update`, so don't delete them

manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: xopclabs
      url-base: https://github.com/xopclabs
    - name: urob
      url-base: https://github.com/urob

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 0f972f1cc3ff416435036d023b62c2e1df6fad96 # main
      import: app/west.yml

    - name: zmk-lang-switch
      remote: xopclabs
      revision: e5d7a731676d3e1adcc62bb6291e2e7c9c4fd9f7 # main
    - name: zmk-helpers
      remote: urob
      revision: 02a97ab09065025e256d81a4eb6b1c5913002318  # main

  self:
    path: config
