# CAUTION! 
# Branch name comments are crucial for `nix run .#update`, so don't delete them

manifest:
  remotes:
    - name: steno
      url-base: https://github.com/lazerwalker
    - name: xopclabs
      url-base: https://github.com/xopclabs
    - name: urob
      url-base: https://github.com/urob

  projects:
    - name: zmk
      remote: steno
      revision: c15c39126aa844b0db8cb0b233463bf17f5c6523 # plover-hid-hog-attempt
      import: app/west.yml

    - name: zmk-lang-switch
      remote: xopclabs
      revision: 3fc9040c83f5216402a20267aaddc110c826bd14 # main
    - name: zmk-helpers
      remote: urob
      revision: b1548efd28d2cc64b9506654e6883695c258190f  # main

  self:
    path: config
