# CAUTION! 
# Branch name comments are crucial for `nix run .#update`, so don't delete them

manifest:
  remotes:
    - name: steno
      #url-base: https://github.com/lazerwalker
      url-base: https://github.com/dnaq

    - name: xopclabs
      url-base: https://github.com/xopclabs
    - name: urob
      url-base: https://github.com/urob

  projects:
    - name: zmk
      remote: steno
      revision: bf9234c602bdf61016f16aa6c2ba179b8ab1623f # plover-hid-hog-attempt
      import: app/west.yml

    - name: zmk-lang-switch
      remote: xopclabs
      revision: d08661e18f27995155709dfca52744accdae3841 # main
    - name: zmk-helpers
      remote: urob
      revision: 230c7e18ee3c82325352287db29b59f53f20fa2a  # main

  self:
    path: config
