# CAUTION! 
# Branch name comments are crucial for `nix run .#update`, so don't delete them

manifest:
  remotes:
    - name: steno
      url-base: https://github.com/lazerwalker
    - name: xopclabs
      url-base: https://github.com/xopclabs
    - name: urob
      url-base: https://github.com/urob

  projects:
    - name: zmk
      remote: steno
      revision: c15c39126aa844b0db8cb0b233463bf17f5c6523 # plover-hid-hog-attempt
      import: app/west.yml

    - name: zmk-lang-switch
      remote: xopclabs
      revision: 738bcb718a2a7288995386b17aba874e8cbd9daf # main
    - name: zmk-helpers
      remote: urob
      revision: d5753b4085049a03cec65f739e04da73bb20a1ff  # main

  self:
    path: config
