manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: xopclabs
      url-base: https://github.com/xopclabs
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 
      import: app/west.yml
    - name: zmk-lang-switch
      remote: xopclabs
      revision: 
  self:
    path: config
